#!/bin/sh
# chkconfig:35 99 1
# description: server manage.
# 需要启动的命令
runPaths="com.demo.geek.DemoTest"
# 启动时间
startTime=`date +%F_%H_%M_%S`
# 服务名
servicename=demoTest
#调试端口
debugPort=804
# JVM参数
JAVA_OPTS="-Xmx1G"
JAVA_OPTS="$JAVA_OPTS -XX:CMSWaitDuration=250"
JAVA_OPTS="$JAVA_OPTS -XX:+UseParNewGC"
JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC"
JAVA_OPTS="$JAVA_OPTS -XX:CMSInitiatingOccupancyFraction=75"
JAVA_OPTS="$JAVA_OPTS -XX:+UseCMSInitiatingOccupancyOnly"
JAVA_OPTS="$JAVA_OPTS -XX:ErrorFile=/demo/log/$servicename/java_error.log.$startTime"

# 调试参数
debugParams=""

# 部署目录
workspace=/demo/core/$servicename


export LANG="zh_CN.UTF-8"

function start(){
    export LANG="zh_CN.UTF-8"
    cd $workspace/bin
    mypid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
    if [ ! -z "$mypid" ]; then
        echo "服务进程存在，3s后重试，请稍候..."
        sleep 3
        mypid=$(ps -ef | grep "$runPaths" | grep -v grep | awk '{print $2}')
        if [ ! -z "$mypid" ]; then
            echo "忽略启动命令：服务进程正在运行"
            return
        fi
    fi
    if [ `whoami` == "root" ]; then
        java -DtaskName=$servicename $JAVA_OPTS $debugParams -classpath .:$workspace/lib/* $runPaths> /dev/null 2>&1 &
    else
        su root --shell=/bin/bash --command="java -DtaskName=$servicename $JAVA_OPTS $debugParams -classpath .:$workspace/lib/* $runPaths>/dev/null 2>&1 &"
    fi
}

function stop(){
    pids=`ps aux|grep java|grep "$runPaths"|awk '{print $2}'`
    echo "关闭$servicename服务($pids)..."
    if [ -n "$pids" ]; then
          for pid in $pids
          do
                    kill $pid
          done
    fi
}


case "$1" in
   start)
       start
       sleep 1
       $0 status
   ;;
   stop)
       stop
       sleep 1
       $0 status
   ;;
   restart)
       stop
       start
       sleep 1
       $0 status
   ;;
   status)
       pids=`ps aux|grep java|grep "$runPaths"|awk '{print $2}'`
       if [ -n "$pids" ]; then
                echo "$servicename服务已启动：($pids).详见/demo/log/$servicename下的相关日志。"
        else
                echo "$servicename启动已停止.详见/demo/log/$servicename下的相关日志。"
        fi
   ;;
   debug)
        stop
        debugParams="-Xdebug -Xrunjdwp:transport=dt_socket,address=$debugPort,server=y,suspend=n"
        start
        echo "$servicename远程调试模式开启中.调试端口为$debugPort。"
        sleep 1
        $0 status
   ;;
   *)
        echo $"Usage: $0 {start|stop|restart|status|debug}"
        exit $?
   ;;
esac